### ISSUE TITLE
I want to cite your research results

### ISSUE THREAD

**Issue by workdd** [ccfelius/queueing#1]
Hello I'm Jaeghang Choi , master student of Kookmin University in South Korea.

I used your queuing codes well in my study, and I'd like like to cite your research results in my paper.

Could you let me know about your any research results or the thing could I cite?

Thank you !

**Comment by ccfelius** [comment]
Of course, go ahead. I've also uploaded the [corresponding paper](https://github.com/ccfelius/queueing/blob/main/queueing_assingment_2021.pdf) that we produced for this assignment.
